// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: media.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createMedia = `-- name: CreateMedia :one
INSERT INTO media (
    id,
    playlist_id,
    title,
    file_url,
    created_at,
    type,
    position,
    added_by_user_id
)
VALUES (
    gen_random_uuid(),
    $1,
    $2,
    $3,
    NOW(),
    $4,
    $5,
    $6
)
RETURNING id, playlist_id, title, file_url, created_at, type, position, added_by_user_id
`

type CreateMediaParams struct {
	PlaylistID    uuid.UUID
	Title         string
	FileUrl       string
	Type          MediaType
	Position      int32
	AddedByUserID uuid.UUID
}

func (q *Queries) CreateMedia(ctx context.Context, arg CreateMediaParams) (Medium, error) {
	row := q.db.QueryRowContext(ctx, createMedia,
		arg.PlaylistID,
		arg.Title,
		arg.FileUrl,
		arg.Type,
		arg.Position,
		arg.AddedByUserID,
	)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.PlaylistID,
		&i.Title,
		&i.FileUrl,
		&i.CreatedAt,
		&i.Type,
		&i.Position,
		&i.AddedByUserID,
	)
	return i, err
}

const getMaxMediaPosition = `-- name: GetMaxMediaPosition :one
SELECT COALESCE(MAX(position), 0)::INTEGER AS max_position
FROM media
WHERE playlist_id = $1
`

func (q *Queries) GetMaxMediaPosition(ctx context.Context, playlistID uuid.UUID) (int32, error) {
	row := q.db.QueryRowContext(ctx, getMaxMediaPosition, playlistID)
	var max_position int32
	err := row.Scan(&max_position)
	return max_position, err
}

const getMediaByPlaylist = `-- name: GetMediaByPlaylist :many
SELECT 
    users.username,
    media.title,
    media.id,
    media.type,
    media.file_url,
    media.position,
    media.created_at
FROM media
INNER JOIN users ON media.added_by_user_id = users.id
WHERE media.playlist_id = $1
ORDER BY media.position ASC
`

type GetMediaByPlaylistRow struct {
	Username  string
	Title     string
	ID        uuid.UUID
	Type      MediaType
	FileUrl   string
	Position  int32
	CreatedAt time.Time
}

func (q *Queries) GetMediaByPlaylist(ctx context.Context, playlistID uuid.UUID) ([]GetMediaByPlaylistRow, error) {
	rows, err := q.db.QueryContext(ctx, getMediaByPlaylist, playlistID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMediaByPlaylistRow
	for rows.Next() {
		var i GetMediaByPlaylistRow
		if err := rows.Scan(
			&i.Username,
			&i.Title,
			&i.ID,
			&i.Type,
			&i.FileUrl,
			&i.Position,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
