// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: playlists.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createPlaylist = `-- name: CreatePlaylist :one
INSERT INTO playlists (
    id,
    user_id,
    name,
    created_at,
    is_public,
    allow_collab_edits
)
VALUES (
    gen_random_uuid(),
    $1,
    $2,
    NOW(),
    $3,
    $4
)
ON CONFLICT DO NOTHING
RETURNING id, user_id, name, created_at, is_public, allow_collab_edits
`

type CreatePlaylistParams struct {
	UserID           uuid.UUID
	Name             string
	IsPublic         bool
	AllowCollabEdits bool
}

func (q *Queries) CreatePlaylist(ctx context.Context, arg CreatePlaylistParams) (Playlist, error) {
	row := q.db.QueryRowContext(ctx, createPlaylist,
		arg.UserID,
		arg.Name,
		arg.IsPublic,
		arg.AllowCollabEdits,
	)
	var i Playlist
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
		&i.IsPublic,
		&i.AllowCollabEdits,
	)
	return i, err
}

const deletePlaylist = `-- name: DeletePlaylist :exec
DELETE FROM playlists
where id = $1
`

func (q *Queries) DeletePlaylist(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deletePlaylist, id)
	return err
}

const getPlaylistByUser = `-- name: GetPlaylistByUser :one
SELECT id, user_id, name, created_at, is_public, allow_collab_edits FROM playlists
WHERE user_id = $1 AND name = $2
`

type GetPlaylistByUserParams struct {
	UserID uuid.UUID
	Name   string
}

func (q *Queries) GetPlaylistByUser(ctx context.Context, arg GetPlaylistByUserParams) (Playlist, error) {
	row := q.db.QueryRowContext(ctx, getPlaylistByUser, arg.UserID, arg.Name)
	var i Playlist
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
		&i.IsPublic,
		&i.AllowCollabEdits,
	)
	return i, err
}

const getUserplaylists = `-- name: GetUserplaylists :many
SELECT id, user_id, name, created_at, is_public, allow_collab_edits FROM playlists
WHERE user_id = $1 OR is_public = TRUE
`

func (q *Queries) GetUserplaylists(ctx context.Context, userID uuid.UUID) ([]Playlist, error) {
	rows, err := q.db.QueryContext(ctx, getUserplaylists, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Playlist
	for rows.Next() {
		var i Playlist
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.CreatedAt,
			&i.IsPublic,
			&i.AllowCollabEdits,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const noneLinkAdded = `-- name: NoneLinkAdded :exec
UPDATE playlists 
SET allow_collab_edits = FALSE, is_public = FALSE
WHERE id = $1
`

func (q *Queries) NoneLinkAdded(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, noneLinkAdded, id)
	return err
}
