// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const checkUserByEmail = `-- name: CheckUserByEmail :one
SELECT id, username, hashed_email, hashed_password, created_at, updated_at FROM users
WHERE hashed_email = $1
`

func (q *Queries) CheckUserByEmail(ctx context.Context, hashedEmail string) (User, error) {
	row := q.db.QueryRowContext(ctx, checkUserByEmail, hashedEmail)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.HashedEmail,
		&i.HashedPassword,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const checkUserByUsername = `-- name: CheckUserByUsername :one
SELECT id, username, hashed_email, hashed_password, created_at, updated_at FROM users
WHERE username = $1
`

func (q *Queries) CheckUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, checkUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.HashedEmail,
		&i.HashedPassword,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    id,
    created_at,
    username,
    hashed_email,
    hashed_password
)
VALUES (
    gen_random_uuid(),
    NOW(),
    $1,
    $2,
    $3
)
RETURNING id, username, hashed_email, hashed_password, created_at, updated_at
`

type CreateUserParams struct {
	Username       string
	HashedEmail    string
	HashedPassword string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Username, arg.HashedEmail, arg.HashedPassword)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.HashedEmail,
		&i.HashedPassword,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUsers = `-- name: DeleteUsers :exec
DELETE FROM users
`

func (q *Queries) DeleteUsers(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteUsers)
	return err
}

const getUserFromRefreshToken = `-- name: GetUserFromRefreshToken :one
SELECT id, username, hashed_email, hashed_password, users.created_at, users.updated_at, token, refresh_tokens.created_at, refresh_tokens.updated_at, user_id, expires_at, revoked_at from users
JOIN refresh_tokens on users.id = refresh_tokens.user_id
WHERE refresh_tokens.token = $1 and refresh_tokens.expires_at > NOW() and refresh_tokens.revoked_at IS NULL
`

type GetUserFromRefreshTokenRow struct {
	ID             uuid.UUID
	Username       string
	HashedEmail    string
	HashedPassword string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Token          string
	CreatedAt_2    time.Time
	UpdatedAt_2    time.Time
	UserID         uuid.UUID
	ExpiresAt      time.Time
	RevokedAt      sql.NullTime
}

func (q *Queries) GetUserFromRefreshToken(ctx context.Context, token string) (GetUserFromRefreshTokenRow, error) {
	row := q.db.QueryRowContext(ctx, getUserFromRefreshToken, token)
	var i GetUserFromRefreshTokenRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.HashedEmail,
		&i.HashedPassword,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Token,
		&i.CreatedAt_2,
		&i.UpdatedAt_2,
		&i.UserID,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET hashed_email = $2, hashed_password = $3, updated_at = NOW()
WHERE $1 = id
RETURNING id, username, hashed_email, hashed_password, created_at, updated_at
`

type UpdateUserParams struct {
	ID             uuid.UUID
	HashedEmail    string
	HashedPassword string
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser, arg.ID, arg.HashedEmail, arg.HashedPassword)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.HashedEmail,
		&i.HashedPassword,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upgradeToRed = `-- name: UpgradeToRed :one
UPDATE users
set is_chirpy_red = TRUE
where $1 = id
RETURNING id, username, hashed_email, hashed_password, created_at, updated_at
`

func (q *Queries) UpgradeToRed(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, upgradeToRed, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.HashedEmail,
		&i.HashedPassword,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
